### ISSUE TITLE
Mapping scala BigDecimal to BSON NumberDecimal instead of binary

### ISSUE THREAD

**Issue by pulewicz** [AVSystem/scala-commons#410]
What is the best to map `scala.math.BigDecimal` to `NumberDecimal` instead of binary? 

I created a repo with this example and currently it looks like that:

```
case class TypeWithBigDecimal(x: BigDecimal, y: BigDecimal)

TypeWithBigDecimal(x = 103234.42343, y = 12344.423)

{"x": {"$binary": {"base64": "AmdTOqcAAAAF", "subType": "00"}}, "y": {"$binary": {"base64": "ALxcZwAAAAM=", "subType": "00"}}}
```

https://github.com/pulewicz/mongo-commons-playground/blob/master/src/main/scala/PlaygroundApp.scala#L89

From what I see, this is currently hardcoded in all of of the Bson outputs, so I guess the only way would be to create your own output implementation, isn't it?

https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonValueOutput.scala#L39
https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonWriterOutput.scala#L26
https://github.com/AVSystem/scala-commons/blob/master/commons-mongo/jvm/src/main/scala/com/avsystem/commons/mongo/BsonWriterOutput.scala#L63

Are you planning to make it configurable?

Regards,
Paweł Ulewicz.

**Comment by ghik** [comment]
Hi,

The problem with `NumberDecimal` is that it's not actually _decimal_ in the same way as Scala's `BigDecimal` is. In fact, the `NumberDecimal` (or `org.bson.types.Decimal128` in Java representation) is a 128-bit _floating point_ representation. This means that its exponent expresses a power of 2 rather than a power of 10. Additionally, `BigDecimal` can be of arbitrary size while `Decimal128` is obviously limited to 128 bits.

The consequence is that some values of `BigDecimal` cannot be precisely represented as `Decimal128`, e.g. the number `0.1` can be represented just fine as `BigDecimal` but representing it with `Decimal128` will lose some precision.

As a workaround, you can use `Decimal128` values directly instead of `BigDecimal`, e.g.

```scala
import com.avsystem.commons.serialization._
import com.avsystem.commons.mongo._
import org.bson.types.Decimal128

case class TypeWithDecimals(x: Decimal128, y: Decimal128)
object TypeWithDecimals extends HasGenCodecWithDeps[BsonGenCodecs.type, TypeWithDecimals]
```

Note: if the `HasGenCodecWithDeps[BsonGenCodecs.type, TypeWithDecimals]` part becomes an annoying boilerplate then it's also possible to create a customized version of `HasGenCodec` which automatically includes additional implicits into `GenCodec` materialization.

**Comment by ghik** [comment]
Hi,

Yes, `Output` implementations should use `Decimal128` representation where possible. Stay tuned for a PR

**Comment by pulewicz** [comment]
Hi,

Thanks for a quick response. For our specific purpose, using `org.bson.types.Decimal128` directly in a case class along with `HasGenCodecWithDep` solved the problem, but a simpler more elegant solution would be even better.

Thanks again for your help.

Regards,
Paweł Ulewicz
