### ISSUE TITLE
Emptiness and Definition of Opt

### ISSUE THREAD

**Issue by halotukozak** [AVSystem/scala-commons#561]
It's common to write tests like
```scala
sth shouldBe Opt.Empty
```

It could be simplified with `org.scalatest.enablers.Emptiness`

```scala
sth shouldBe empty
```

Possible implementation

```scala
implicit def emptinessOfOpt[A]: Emptiness[Opt[A]] = _.isEmpty
```

Even more useful, the same for `org.scalatest.enablers.Definition`

Tbh, I don't know if it's possible to do it without requiring the `scalaTest` dependency.

**Comment by ddworak** [comment]
Should `Opt` not be a value class, the exotic feature of duck-typing in Scala would provide an instance of `Emptiness` for `Opt` based on `org.scalatest.enablers.Emptiness#emptinessOfAnyRefWithParameterlessIsEmptyMethod`.

Providing an instance in the `Opt` companion is not an option, as it would require bringing `ScalaTest` dependency to runtime library. Therefore, we'd have to ship a separate test support library. This would mean introducing an import or extension in order to bring this typeclass into the implicit scope, which looks worse than what we started with.

In general, I think this is much work for very little profit, as your original example is very readable. If you do not like the error message, you can always switch it up a bit to:
```scala
opt.iterator shouldBe empty
```
using any conversion method. Real programmers (like the ones in https://www.ee.torontomu.ca/~elf/hack/realmen.html or @ghik) would recommend using:
```scala
assert(opt.isEmpty)
```
which is the least you can do for the most you can get.

If you want to, throw the typeclass instance into your base test class and write some prose in Scala tests. Sometimes it's what one really needs to make himself happy.
