### ISSUE TITLE
Unexpected stack overflow error during serialization of an acyclic graph of nested structures

### ISSUE THREAD

**Issue by plokhotnyuk** [AVSystem/scala-commons#62]
To reproduce, please uncomment the following test and method that it calls:
https://github.com/plokhotnyuk/jsoniter-scala/pull/127/files#diff-feb5716779d1ff5fbe1a4af25bb4ae6dR19

**Comment by ghik** [comment]
Hello, thanks for the report.
The problem is in this line: https://github.com/plokhotnyuk/jsoniter-scala/blob/3f81687acabc30202d43c2a9f31fb541fb342112/benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/AVSystemCodecs.scala#L48

```scala
implicit val twitterAPIGenCodec: GenCodec[Seq[Tweet]] = GenCodec.materializeRecursively[Seq[Tweet]]
```

You should not macro-materialize codec for a `Seq`, because `GenCodec[Seq[A]]` is automatically provided as long as there is a `GenCodec[A]`, so this would be sufficient:

```scala
implicit val twitterAPIGenCodec: GenCodec[Tweet] = GenCodec.materializeRecursively[Tweet]
```

... but I just realized that it doesn't work because `GenCodec` cannot be materialized for case classes with more than 22 fields :cry: 
Also, the macro itself should be more secured to reject materializing something like a `Seq`.

**Comment by ghik** [comment]
This is interesting. It turns out that `Seq[String]` is actually a completely valid type for macro materialization of `GenCodec` because it has a companion object with matching `apply` and `unapplySeq` methods. The only problem is that the argument of `apply` is also a `Seq[String]` which creates a cycle and causes stack to overflow.

**Comment by plokhotnyuk** [comment]
Stack overflow is cannot be reproduced by this code with v1.28.2, but `JsonStringInput.read[Seq[Tweet]]` [returns] (https://github.com/plokhotnyuk/jsoniter-scala/blob/7aa20826271d03262b734caa40d818bda5f725d3/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/TwitterAPIBenchmark.scala#L25-L28) an instance of `Vector` instead of expected `List`.

Should I close this issue and open a new one for that case?

**Comment by ghik** [comment]
@plokhotnyuk I've created separate issue for that, closing this one. Thanks!
