### ISSUE TITLE
GenCodec serializes byte arrays to a base16 encoded string

### ISSUE THREAD

**Issue by plokhotnyuk** [AVSystem/scala-commons#64]
It should be documented somewhere in the `GenCodec` docs: https://github.com/AVSystem/scala-commons/blob/master/docs/GenCodec.md

How this representation can be altered to JSON arrays of numbers or base64 encoded strings?

**Comment by ghik** [comment]
It's more an implementation detail of `JsonStringInput/Output` rather than `GenCodec` itself. The solution would be to make `JsonStringInput/Output` more generic/configurable. You could also provide your own implementations of JSON input/output by e.g. subclassing `JsonStringInput/Output` and overriding `read/writeObject`, `read/writeList` and `read/writeBinary` in an appropriate way.

**Comment by ghik** [comment]
Fixed as part of #66 in #74, byte arrays are serialized as JSON arrays of signed byte numeric values by default. This can be configured using `JsonOptions` - the other format to choose is hex string.
