### ISSUE TITLE
More user-friendly support of value classes

### ISSUE THREAD

**Issue by plokhotnyuk** [AVSystem/scala-commons#91]
Currently `IntVal(1)` value of `case class IntVal(value: Int) extends AnyVal` type is serialized to `{"value":1}`. It would be much handy to avoid wrapping of such values by extra JSON objects and serialize/parse just underlying value instead.
 
Also, codecs for value types can be generated fully automatically to reduce need of semi-auto materialization like here:
https://github.com/plokhotnyuk/jsoniter-scala/pull/195/files

**Comment by ghik** [comment]
Hello @plokhotnyuk, you can use [@transparent](http://avsystem.github.io/scala-commons/api/com/avsystem/commons/serialization/transparent.html) for that, e.g.

```scala
@transparent case class IntVal(value: Int) extends AnyVal
object IntVal extends HasGenCodec[IntVal]
```

Doing this automatically for all value classes is IMHO not the best idea because someone might want to refactor a case class (which happens to be a value class just because it has one field at the moment) by adding fields to it. With the default "wrapping" encoding it's possible to do this without breaking backwards compatibility (as long as new fields have default values). So in my opinion it should be a conscious decision of the programmer to use "transparent" encoding and the annotation is made exactly for that purpose.

**Comment by plokhotnyuk** [comment]
@ghik thank you a lot, I have used the `@transparent` annotation for value classes:

https://github.com/plokhotnyuk/jsoniter-scala/commit/1301f7708eca1ddd55fa8df9f213ac554aedcc39
